// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Jelmer de Hen

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: demangle.proto

package demanglepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Demangle_Demangle_FullMethodName       = "/demangle.v1.Demangle/Demangle"
	Demangle_Detect_FullMethodName         = "/demangle.v1.Demangle/Detect"
	Demangle_Schemes_FullMethodName        = "/demangle.v1.Demangle/Schemes"
	Demangle_DemangleStream_FullMethodName = "/demangle.v1.Demangle/DemangleStream"
	Demangle_UploadContext_FullMethodName  = "/demangle.v1.Demangle/UploadContext"
	Demangle_ListContexts_FullMethodName   = "/demangle.v1.Demangle/ListContexts"
	Demangle_DeleteContext_FullMethodName  = "/demangle.v1.Demangle/DeleteContext"
	Demangle_Mangle_FullMethodName         = "/demangle.v1.Demangle/Mangle"
)

// DemangleClient is the client API for Demangle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Demangle is the wire-level mirror of the github.com/jelmerdehen/demangle
// library surface.
type DemangleClient interface {
	Demangle(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error)
	Schemes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SchemesResponse, error)
	DemangleStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error)
	UploadContext(ctx context.Context, in *UploadContextRequest, opts ...grpc.CallOption) (*UploadContextResponse, error)
	ListContexts(ctx context.Context, in *ListContextsRequest, opts ...grpc.CallOption) (*ListContextsResponse, error)
	DeleteContext(ctx context.Context, in *DeleteContextRequest, opts ...grpc.CallOption) (*Empty, error)
	// Mangle is the inverse of Demangle. The caller supplies a raw demangled
	// symbol string (req.input) and the target scheme (req.scheme); the server
	// demangling-parses it to a Node tree and then re-mangles it.
	Mangle(ctx context.Context, in *MangleRequest, opts ...grpc.CallOption) (*MangleResponse, error)
}

type demangleClient struct {
	cc grpc.ClientConnInterface
}

func NewDemangleClient(cc grpc.ClientConnInterface) DemangleClient {
	return &demangleClient{cc}
}

func (c *demangleClient) Demangle(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Demangle_Demangle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demangleClient) Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectResponse)
	err := c.cc.Invoke(ctx, Demangle_Detect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demangleClient) Schemes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SchemesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchemesResponse)
	err := c.cc.Invoke(ctx, Demangle_Schemes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demangleClient) DemangleStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Demangle_ServiceDesc.Streams[0], Demangle_DemangleStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Demangle_DemangleStreamClient = grpc.BidiStreamingClient[Request, Response]

func (c *demangleClient) UploadContext(ctx context.Context, in *UploadContextRequest, opts ...grpc.CallOption) (*UploadContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadContextResponse)
	err := c.cc.Invoke(ctx, Demangle_UploadContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demangleClient) ListContexts(ctx context.Context, in *ListContextsRequest, opts ...grpc.CallOption) (*ListContextsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContextsResponse)
	err := c.cc.Invoke(ctx, Demangle_ListContexts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demangleClient) DeleteContext(ctx context.Context, in *DeleteContextRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Demangle_DeleteContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demangleClient) Mangle(ctx context.Context, in *MangleRequest, opts ...grpc.CallOption) (*MangleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MangleResponse)
	err := c.cc.Invoke(ctx, Demangle_Mangle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemangleServer is the server API for Demangle service.
// All implementations must embed UnimplementedDemangleServer
// for forward compatibility.
//
// Demangle is the wire-level mirror of the github.com/jelmerdehen/demangle
// library surface.
type DemangleServer interface {
	Demangle(context.Context, *Request) (*Response, error)
	Detect(context.Context, *DetectRequest) (*DetectResponse, error)
	Schemes(context.Context, *Empty) (*SchemesResponse, error)
	DemangleStream(grpc.BidiStreamingServer[Request, Response]) error
	UploadContext(context.Context, *UploadContextRequest) (*UploadContextResponse, error)
	ListContexts(context.Context, *ListContextsRequest) (*ListContextsResponse, error)
	DeleteContext(context.Context, *DeleteContextRequest) (*Empty, error)
	// Mangle is the inverse of Demangle. The caller supplies a raw demangled
	// symbol string (req.input) and the target scheme (req.scheme); the server
	// demangling-parses it to a Node tree and then re-mangles it.
	Mangle(context.Context, *MangleRequest) (*MangleResponse, error)
	mustEmbedUnimplementedDemangleServer()
}

// UnimplementedDemangleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDemangleServer struct{}

func (UnimplementedDemangleServer) Demangle(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Demangle not implemented")
}
func (UnimplementedDemangleServer) Detect(context.Context, *DetectRequest) (*DetectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Detect not implemented")
}
func (UnimplementedDemangleServer) Schemes(context.Context, *Empty) (*SchemesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Schemes not implemented")
}
func (UnimplementedDemangleServer) DemangleStream(grpc.BidiStreamingServer[Request, Response]) error {
	return status.Error(codes.Unimplemented, "method DemangleStream not implemented")
}
func (UnimplementedDemangleServer) UploadContext(context.Context, *UploadContextRequest) (*UploadContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadContext not implemented")
}
func (UnimplementedDemangleServer) ListContexts(context.Context, *ListContextsRequest) (*ListContextsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContexts not implemented")
}
func (UnimplementedDemangleServer) DeleteContext(context.Context, *DeleteContextRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteContext not implemented")
}
func (UnimplementedDemangleServer) Mangle(context.Context, *MangleRequest) (*MangleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Mangle not implemented")
}
func (UnimplementedDemangleServer) mustEmbedUnimplementedDemangleServer() {}
func (UnimplementedDemangleServer) testEmbeddedByValue()                  {}

// UnsafeDemangleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DemangleServer will
// result in compilation errors.
type UnsafeDemangleServer interface {
	mustEmbedUnimplementedDemangleServer()
}

func RegisterDemangleServer(s grpc.ServiceRegistrar, srv DemangleServer) {
	// If the following call panics, it indicates UnimplementedDemangleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Demangle_ServiceDesc, srv)
}

func _Demangle_Demangle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemangleServer).Demangle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Demangle_Demangle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemangleServer).Demangle(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demangle_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemangleServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Demangle_Detect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemangleServer).Detect(ctx, req.(*DetectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demangle_Schemes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemangleServer).Schemes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Demangle_Schemes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemangleServer).Schemes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demangle_DemangleStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DemangleServer).DemangleStream(&grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Demangle_DemangleStreamServer = grpc.BidiStreamingServer[Request, Response]

func _Demangle_UploadContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemangleServer).UploadContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Demangle_UploadContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemangleServer).UploadContext(ctx, req.(*UploadContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demangle_ListContexts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContextsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemangleServer).ListContexts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Demangle_ListContexts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemangleServer).ListContexts(ctx, req.(*ListContextsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demangle_DeleteContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemangleServer).DeleteContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Demangle_DeleteContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemangleServer).DeleteContext(ctx, req.(*DeleteContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demangle_Mangle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MangleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemangleServer).Mangle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Demangle_Mangle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemangleServer).Mangle(ctx, req.(*MangleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Demangle_ServiceDesc is the grpc.ServiceDesc for Demangle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Demangle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "demangle.v1.Demangle",
	HandlerType: (*DemangleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Demangle",
			Handler:    _Demangle_Demangle_Handler,
		},
		{
			MethodName: "Detect",
			Handler:    _Demangle_Detect_Handler,
		},
		{
			MethodName: "Schemes",
			Handler:    _Demangle_Schemes_Handler,
		},
		{
			MethodName: "UploadContext",
			Handler:    _Demangle_UploadContext_Handler,
		},
		{
			MethodName: "ListContexts",
			Handler:    _Demangle_ListContexts_Handler,
		},
		{
			MethodName: "DeleteContext",
			Handler:    _Demangle_DeleteContext_Handler,
		},
		{
			MethodName: "Mangle",
			Handler:    _Demangle_Mangle_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DemangleStream",
			Handler:       _Demangle_DemangleStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "demangle.proto",
}
