// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Jelmer de Hen

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: demangle.proto

package demanglepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_demangle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_demangle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_demangle_proto_rawDescGZIP(), []int{0}
}

type Options struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Simplified                    bool                   `protobuf:"varint,1,opt,name=simplified,proto3" json:"simplified,omitempty"`
	SynthesizeSugar               bool                   `protobuf:"varint,2,opt,name=synthesize_sugar,json=synthesizeSugar,proto3" json:"synthesize_sugar,omitempty"`
	QualifyEntities               bool                   `protobuf:"varint,3,opt,name=qualify_entities,json=qualifyEntities,proto3" json:"qualify_entities,omitempty"`
	DisplayGenericSpecialisations bool                   `protobuf:"varint,4,opt,name=display_generic_specialisations,json=displayGenericSpecialisations,proto3" json:"display_generic_specialisations,omitempty"`
	DisplayThunks                 bool                   `protobuf:"varint,5,opt,name=display_thunks,json=displayThunks,proto3" json:"display_thunks,omitempty"`
	ReturnTree                    bool                   `protobuf:"varint,6,opt,name=return_tree,json=returnTree,proto3" json:"return_tree,omitempty"`
	VerifyRoundTrip               bool                   `protobuf:"varint,7,opt,name=verify_round_trip,json=verifyRoundTrip,proto3" json:"verify_round_trip,omitempty"`
	AllowLegacy                   bool                   `protobuf:"varint,8,opt,name=allow_legacy,json=allowLegacy,proto3" json:"allow_legacy,omitempty"`
	BestEffortMangle              bool                   `protobuf:"varint,9,opt,name=best_effort_mangle,json=bestEffortMangle,proto3" json:"best_effort_mangle,omitempty"`
	SchemeSpecific                map[string]string      `protobuf:"bytes,10,rep,name=scheme_specific,json=schemeSpecific,proto3" json:"scheme_specific,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Context is referenced by sha256 from the server's ContextStore.
	// Empty means "no context." Contexts are uploaded via UploadContext.
	ContextSha256 string `protobuf:"bytes,11,opt,name=context_sha256,json=contextSha256,proto3" json:"context_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_demangle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_demangle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_demangle_proto_rawDescGZIP(), []int{1}
}

func (x *Options) GetSimplified() bool {
	if x != nil {
		return x.Simplified
	}
	return false
}

func (x *Options) GetSynthesizeSugar() bool {
	if x != nil {
		return x.SynthesizeSugar
	}
	return false
}

func (x *Options) GetQualifyEntities() bool {
	if x != nil {
		return x.QualifyEntities
	}
	return false
}

func (x *Options) GetDisplayGenericSpecialisations() bool {
	if x != nil {
		return x.DisplayGenericSpecialisations
	}
	return false
}

func (x *Options) GetDisplayThunks() bool {
	if x != nil {
		return x.DisplayThunks
	}
	return false
}

func (x *Options) GetReturnTree() bool {
	if x != nil {
		return x.ReturnTree
	}
	return false
}

func (x *Options) GetVerifyRoundTrip() bool {
	if x != nil {
		return x.VerifyRoundTrip
	}
	return false
}

func (x *Options) GetAllowLegacy() bool {
	if x != nil {
		return x.AllowLegacy
	}
	return false
}

func (x *Options) GetBestEffortMangle() bool {
	if x != nil {
		return x.BestEffortMangle
	}
	return false
}

func (x *Options) GetSchemeSpecific() map[string]string {
	if x != nil {
		return x.SchemeSpecific
	}
	return nil
}

func (x *Options) GetContextSha256() string {
	if x != nil {
		return x.ContextSha256
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Scheme        string                 `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty"` // empty = auto-detect
	Options       *Options               `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	Id            uint64                 `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"` // caller-supplied correlation id for streaming
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_demangle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_demangle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_demangle_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *Request) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Request) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Annotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Annotation) Reset() {
	*x = Annotation{}
	mi := &file_demangle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Annotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Annotation) ProtoMessage() {}

func (x *Annotation) ProtoReflect() protoreflect.Message {
	mi := &file_demangle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Annotation.ProtoReflect.Descriptor instead.
func (*Annotation) Descriptor() ([]byte, []int) {
	return file_demangle_proto_rawDescGZIP(), []int{3}
}

func (x *Annotation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Annotation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheme        string                 `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Kind          int32                  `protobuf:"varint,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Index         uint64                 `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	Children      []*Node                `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	Attrs         []*Annotation          `protobuf:"bytes,6,rep,name=attrs,proto3" json:"attrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_demangle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_demangle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_demangle_proto_rawDescGZIP(), []int{4}
}

func (x *Node) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Node) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *Node) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Node) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Node) GetChildren() []*Node {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *Node) GetAttrs() []*Annotation {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          int32                  `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"` // demangle.ErrKind
	Scheme        string                 `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Expected      string                 `protobuf:"bytes,4,opt,name=expected,proto3" json:"expected,omitempty"`
	Got           string                 `protobuf:"bytes,5,opt,name=got,proto3" json:"got,omitempty"`
	Window        string                 `protobuf:"bytes,6,opt,name=window,proto3" json:"window,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"` // humanised form
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_demangle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_demangle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_demangle_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *Error) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Error) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Error) GetExpected() string {
	if x != nil {
		return x.Expected
	}
	return ""
}

func (x *Error) GetGot() string {
	if x != nil {
		return x.Got
	}
	return ""
}

func (x *Error) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Scheme        string                 `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Input         string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Confidence    int32                  `protobuf:"varint,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Annotations   []*Annotation          `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations,omitempty"`
	Tree          *Node                  `protobuf:"bytes,7,opt,name=tree,proto3" json:"tree,omitempty"` // nil unless Options.return_tree
	Partial       bool                   `protobuf:"varint,8,opt,name=partial,proto3" json:"partial,omitempty"`
	LostInfo      []string               `protobuf:"bytes,9,rep,name=lost_info,json=lostInfo,proto3" json:"lost_info,omitempty"`
	Err           *Error                 `protobuf:"bytes,10,opt,name=err,proto3" json:"err,omitempty"` // nil on success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_demangle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_demangle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_demangle_proto_rawDescGZIP(), []int{6}
}

func (x *Response) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Response) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Response) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *Response) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *Response) GetConfidence() int32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Response) GetAnnotations() []*Annotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Response) GetTree() *Node {
	if x != nil {
		return x.Tree
	}
	return nil
}

func (x *Response) GetPartial() bool {
	if x != nil {
		return x.Partial
	}
	return false
}

func (x *Response) GetLostInfo() []string {
	if x != nil {
		return x.LostInfo
	}
	return nil
}

func (x *Response) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type DetectRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Input            string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	MaxCandidates    int32                  `protobuf:"varint,2,opt,name=max_candidates,json=maxCandidates,proto3" json:"max_candidates,omitempty"`
	MinConfidence    int32                  `protobuf:"varint,3,opt,name=min_confidence,json=minConfidence,proto3" json:"min_confidence,omitempty"`
	IncludeWeak      bool                   `protobuf:"varint,4,opt,name=include_weak,json=includeWeak,proto3" json:"include_weak,omitempty"`
	SchemeHintFamily string                 `protobuf:"bytes,5,opt,name=scheme_hint_family,json=schemeHintFamily,proto3" json:"scheme_hint_family,omitempty"`
	Strict           bool                   `protobuf:"varint,6,opt,name=strict,proto3" json:"strict,omitempty"`
	AmbiguityWindow  int32                  `protobuf:"varint,7,opt,name=ambiguity_window,json=ambiguityWindow,proto3" json:"ambiguity_window,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DetectRequest) Reset() {
	*x = DetectRequest{}
	mi := &file_demangle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectRequest) ProtoMessage() {}

func (x *DetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demangle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectRequest.ProtoReflect.Descriptor instead.
func (*DetectRequest) Descriptor() ([]byte, []int) {
	return file_demangle_proto_rawDescGZIP(), []int{7}
}

func (x *DetectRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *DetectRequest) GetMaxCandidates() int32 {
	if x != nil {
		return x.MaxCandidates
	}
	return 0
}

func (x *DetectRequest) GetMinConfidence() int32 {
	if x != nil {
		return x.MinConfidence
	}
	return 0
}

func (x *DetectRequest) GetIncludeWeak() bool {
	if x != nil {
		return x.IncludeWeak
	}
	return false
}

func (x *DetectRequest) GetSchemeHintFamily() string {
	if x != nil {
		return x.SchemeHintFamily
	}
	return ""
}

func (x *DetectRequest) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

func (x *DetectRequest) GetAmbiguityWindow() int32 {
	if x != nil {
		return x.AmbiguityWindow
	}
	return 0
}

type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheme        string                 `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Confidence    int32                  `protobuf:"varint,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Signals       []string               `protobuf:"bytes,3,rep,name=signals,proto3" json:"signals,omitempty"`
	Negatives     []string               `protobuf:"bytes,4,rep,name=negatives,proto3" json:"negatives,omitempty"`
	Diagnostic    string                 `protobuf:"bytes,5,opt,name=diagnostic,proto3" json:"diagnostic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_demangle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_demangle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_demangle_proto_rawDescGZIP(), []int{8}
}

func (x *Candidate) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Candidate) GetConfidence() int32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Candidate) GetSignals() []string {
	if x != nil {
		return x.Signals
	}
	return nil
}

func (x *Candidate) GetNegatives() []string {
	if x != nil {
		return x.Negatives
	}
	return nil
}

func (x *Candidate) GetDiagnostic() string {
	if x != nil {
		return x.Diagnostic
	}
	return ""
}

type DetectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*Candidate           `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectResponse) Reset() {
	*x = DetectResponse{}
	mi := &file_demangle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectResponse) ProtoMessage() {}

func (x *DetectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demangle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectResponse.ProtoReflect.Descriptor instead.
func (*DetectResponse) Descriptor() ([]byte, []int) {
	return file_demangle_proto_rawDescGZIP(), []int{9}
}

func (x *DetectResponse) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type SchemeInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Family            string                 `protobuf:"bytes,2,opt,name=family,proto3" json:"family,omitempty"`
	Version           string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description       string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Stability         string                 `protobuf:"bytes,5,opt,name=stability,proto3" json:"stability,omitempty"`                                 // "stable" | "experimental" | "deprecated"
	MangleFidelity    string                 `protobuf:"bytes,6,opt,name=mangle_fidelity,json=mangleFidelity,proto3" json:"mangle_fidelity,omitempty"` // "exact" | "canonical" | "best-effort" | "none"
	ImplementsMangler bool                   `protobuf:"varint,7,opt,name=implements_mangler,json=implementsMangler,proto3" json:"implements_mangler,omitempty"`
	MaxInputBytes     int32                  `protobuf:"varint,8,opt,name=max_input_bytes,json=maxInputBytes,proto3" json:"max_input_bytes,omitempty"`
	RequiresContext   []string               `protobuf:"bytes,9,rep,name=requires_context,json=requiresContext,proto3" json:"requires_context,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SchemeInfo) Reset() {
	*x = SchemeInfo{}
	mi := &file_demangle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemeInfo) ProtoMessage() {}

func (x *SchemeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_demangle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemeInfo.ProtoReflect.Descriptor instead.
func (*SchemeInfo) Descriptor() ([]byte, []int) {
	return file_demangle_proto_rawDescGZIP(), []int{10}
}

func (x *SchemeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemeInfo) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *SchemeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SchemeInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SchemeInfo) GetStability() string {
	if x != nil {
		return x.Stability
	}
	return ""
}

func (x *SchemeInfo) GetMangleFidelity() string {
	if x != nil {
		return x.MangleFidelity
	}
	return ""
}

func (x *SchemeInfo) GetImplementsMangler() bool {
	if x != nil {
		return x.ImplementsMangler
	}
	return false
}

func (x *SchemeInfo) GetMaxInputBytes() int32 {
	if x != nil {
		return x.MaxInputBytes
	}
	return 0
}

func (x *SchemeInfo) GetRequiresContext() []string {
	if x != nil {
		return x.RequiresContext
	}
	return nil
}

type SchemesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schemes       []*SchemeInfo          `protobuf:"bytes,1,rep,name=schemes,proto3" json:"schemes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemesResponse) Reset() {
	*x = SchemesResponse{}
	mi := &file_demangle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemesResponse) ProtoMessage() {}

func (x *SchemesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demangle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemesResponse.ProtoReflect.Descriptor instead.
func (*SchemesResponse) Descriptor() ([]byte, []int) {
	return file_demangle_proto_rawDescGZIP(), []int{11}
}

func (x *SchemesResponse) GetSchemes() []*SchemeInfo {
	if x != nil {
		return x.Schemes
	}
	return nil
}

type UploadContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // "proguard_map" | "js_source_map" | …
	Blob          []byte                 `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadContextRequest) Reset() {
	*x = UploadContextRequest{}
	mi := &file_demangle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadContextRequest) ProtoMessage() {}

func (x *UploadContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demangle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadContextRequest.ProtoReflect.Descriptor instead.
func (*UploadContextRequest) Descriptor() ([]byte, []int) {
	return file_demangle_proto_rawDescGZIP(), []int{12}
}

func (x *UploadContextRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *UploadContextRequest) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *UploadContextRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UploadContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	ByteSize      int64                  `protobuf:"varint,2,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadContextResponse) Reset() {
	*x = UploadContextResponse{}
	mi := &file_demangle_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadContextResponse) ProtoMessage() {}

func (x *UploadContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demangle_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadContextResponse.ProtoReflect.Descriptor instead.
func (*UploadContextResponse) Descriptor() ([]byte, []int) {
	return file_demangle_proto_rawDescGZIP(), []int{13}
}

func (x *UploadContextResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *UploadContextResponse) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

type ContextInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	ByteSize      int64                  `protobuf:"varint,3,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	UploadedTs    int64                  `protobuf:"varint,4,opt,name=uploaded_ts,json=uploadedTs,proto3" json:"uploaded_ts,omitempty"` // unix seconds
	LastAccessTs  int64                  `protobuf:"varint,5,opt,name=last_access_ts,json=lastAccessTs,proto3" json:"last_access_ts,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextInfo) Reset() {
	*x = ContextInfo{}
	mi := &file_demangle_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextInfo) ProtoMessage() {}

func (x *ContextInfo) ProtoReflect() protoreflect.Message {
	mi := &file_demangle_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextInfo.ProtoReflect.Descriptor instead.
func (*ContextInfo) Descriptor() ([]byte, []int) {
	return file_demangle_proto_rawDescGZIP(), []int{14}
}

func (x *ContextInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ContextInfo) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ContextInfo) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

func (x *ContextInfo) GetUploadedTs() int64 {
	if x != nil {
		return x.UploadedTs
	}
	return 0
}

func (x *ContextInfo) GetLastAccessTs() int64 {
	if x != nil {
		return x.LastAccessTs
	}
	return 0
}

func (x *ContextInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListContextsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // empty = all kinds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContextsRequest) Reset() {
	*x = ListContextsRequest{}
	mi := &file_demangle_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContextsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContextsRequest) ProtoMessage() {}

func (x *ListContextsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demangle_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContextsRequest.ProtoReflect.Descriptor instead.
func (*ListContextsRequest) Descriptor() ([]byte, []int) {
	return file_demangle_proto_rawDescGZIP(), []int{15}
}

func (x *ListContextsRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type ListContextsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contexts      []*ContextInfo         `protobuf:"bytes,1,rep,name=contexts,proto3" json:"contexts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContextsResponse) Reset() {
	*x = ListContextsResponse{}
	mi := &file_demangle_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContextsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContextsResponse) ProtoMessage() {}

func (x *ListContextsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demangle_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContextsResponse.ProtoReflect.Descriptor instead.
func (*ListContextsResponse) Descriptor() ([]byte, []int) {
	return file_demangle_proto_rawDescGZIP(), []int{16}
}

func (x *ListContextsResponse) GetContexts() []*ContextInfo {
	if x != nil {
		return x.Contexts
	}
	return nil
}

type DeleteContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContextRequest) Reset() {
	*x = DeleteContextRequest{}
	mi := &file_demangle_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContextRequest) ProtoMessage() {}

func (x *DeleteContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demangle_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContextRequest.ProtoReflect.Descriptor instead.
func (*DeleteContextRequest) Descriptor() ([]byte, []int) {
	return file_demangle_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteContextRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

var File_demangle_proto protoreflect.FileDescriptor

const file_demangle_proto_rawDesc = "" +
	"\n" +
	"\x0edemangle.proto\x12\vdemangle.v1\"\a\n" +
	"\x05Empty\"\xc9\x04\n" +
	"\aOptions\x12\x1e\n" +
	"\n" +
	"simplified\x18\x01 \x01(\bR\n" +
	"simplified\x12)\n" +
	"\x10synthesize_sugar\x18\x02 \x01(\bR\x0fsynthesizeSugar\x12)\n" +
	"\x10qualify_entities\x18\x03 \x01(\bR\x0fqualifyEntities\x12F\n" +
	"\x1fdisplay_generic_specialisations\x18\x04 \x01(\bR\x1ddisplayGenericSpecialisations\x12%\n" +
	"\x0edisplay_thunks\x18\x05 \x01(\bR\rdisplayThunks\x12\x1f\n" +
	"\vreturn_tree\x18\x06 \x01(\bR\n" +
	"returnTree\x12*\n" +
	"\x11verify_round_trip\x18\a \x01(\bR\x0fverifyRoundTrip\x12!\n" +
	"\fallow_legacy\x18\b \x01(\bR\vallowLegacy\x12,\n" +
	"\x12best_effort_mangle\x18\t \x01(\bR\x10bestEffortMangle\x12Q\n" +
	"\x0fscheme_specific\x18\n" +
	" \x03(\v2(.demangle.v1.Options.SchemeSpecificEntryR\x0eschemeSpecific\x12%\n" +
	"\x0econtext_sha256\x18\v \x01(\tR\rcontextSha256\x1aA\n" +
	"\x13SchemeSpecificEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"w\n" +
	"\aRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x12\x16\n" +
	"\x06scheme\x18\x02 \x01(\tR\x06scheme\x12.\n" +
	"\aoptions\x18\x03 \x01(\v2\x14.demangle.v1.OptionsR\aoptions\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x04R\x02id\"4\n" +
	"\n" +
	"Annotation\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xba\x01\n" +
	"\x04Node\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\x05R\x04kind\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x14\n" +
	"\x05index\x18\x04 \x01(\x04R\x05index\x12-\n" +
	"\bchildren\x18\x05 \x03(\v2\x11.demangle.v1.NodeR\bchildren\x12-\n" +
	"\x05attrs\x18\x06 \x03(\v2\x17.demangle.v1.AnnotationR\x05attrs\"\xab\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\x05R\x04kind\x12\x16\n" +
	"\x06scheme\x18\x02 \x01(\tR\x06scheme\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x1a\n" +
	"\bexpected\x18\x04 \x01(\tR\bexpected\x12\x10\n" +
	"\x03got\x18\x05 \x01(\tR\x03got\x12\x16\n" +
	"\x06window\x18\x06 \x01(\tR\x06window\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\"\xbf\x02\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06scheme\x18\x02 \x01(\tR\x06scheme\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x05R\n" +
	"confidence\x129\n" +
	"\vannotations\x18\x06 \x03(\v2\x17.demangle.v1.AnnotationR\vannotations\x12%\n" +
	"\x04tree\x18\a \x01(\v2\x11.demangle.v1.NodeR\x04tree\x12\x18\n" +
	"\apartial\x18\b \x01(\bR\apartial\x12\x1b\n" +
	"\tlost_info\x18\t \x03(\tR\blostInfo\x12$\n" +
	"\x03err\x18\n" +
	" \x01(\v2\x12.demangle.v1.ErrorR\x03err\"\x87\x02\n" +
	"\rDetectRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x12%\n" +
	"\x0emax_candidates\x18\x02 \x01(\x05R\rmaxCandidates\x12%\n" +
	"\x0emin_confidence\x18\x03 \x01(\x05R\rminConfidence\x12!\n" +
	"\finclude_weak\x18\x04 \x01(\bR\vincludeWeak\x12,\n" +
	"\x12scheme_hint_family\x18\x05 \x01(\tR\x10schemeHintFamily\x12\x16\n" +
	"\x06strict\x18\x06 \x01(\bR\x06strict\x12)\n" +
	"\x10ambiguity_window\x18\a \x01(\x05R\x0fambiguityWindow\"\x9b\x01\n" +
	"\tCandidate\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x05R\n" +
	"confidence\x12\x18\n" +
	"\asignals\x18\x03 \x03(\tR\asignals\x12\x1c\n" +
	"\tnegatives\x18\x04 \x03(\tR\tnegatives\x12\x1e\n" +
	"\n" +
	"diagnostic\x18\x05 \x01(\tR\n" +
	"diagnostic\"H\n" +
	"\x0eDetectResponse\x126\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x16.demangle.v1.CandidateR\n" +
	"candidates\"\xbd\x02\n" +
	"\n" +
	"SchemeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06family\x18\x02 \x01(\tR\x06family\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\tstability\x18\x05 \x01(\tR\tstability\x12'\n" +
	"\x0fmangle_fidelity\x18\x06 \x01(\tR\x0emangleFidelity\x12-\n" +
	"\x12implements_mangler\x18\a \x01(\bR\x11implementsMangler\x12&\n" +
	"\x0fmax_input_bytes\x18\b \x01(\x05R\rmaxInputBytes\x12)\n" +
	"\x10requires_context\x18\t \x03(\tR\x0frequiresContext\"D\n" +
	"\x0fSchemesResponse\x121\n" +
	"\aschemes\x18\x01 \x03(\v2\x17.demangle.v1.SchemeInfoR\aschemes\"\xc8\x01\n" +
	"\x14UploadContextRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04blob\x18\x02 \x01(\fR\x04blob\x12K\n" +
	"\bmetadata\x18\x03 \x03(\v2/.demangle.v1.UploadContextRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x15UploadContextResponse\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x1b\n" +
	"\tbyte_size\x18\x02 \x01(\x03R\bbyteSize\"\x9e\x02\n" +
	"\vContextInfo\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\x1b\n" +
	"\tbyte_size\x18\x03 \x01(\x03R\bbyteSize\x12\x1f\n" +
	"\vuploaded_ts\x18\x04 \x01(\x03R\n" +
	"uploadedTs\x12$\n" +
	"\x0elast_access_ts\x18\x05 \x01(\x03R\flastAccessTs\x12B\n" +
	"\bmetadata\x18\x06 \x03(\v2&.demangle.v1.ContextInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\x13ListContextsRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"L\n" +
	"\x14ListContextsResponse\x124\n" +
	"\bcontexts\x18\x01 \x03(\v2\x18.demangle.v1.ContextInfoR\bcontexts\".\n" +
	"\x14DeleteContextRequest\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha2562\xfb\x03\n" +
	"\bDemangle\x127\n" +
	"\bDemangle\x12\x14.demangle.v1.Request\x1a\x15.demangle.v1.Response\x12A\n" +
	"\x06Detect\x12\x1a.demangle.v1.DetectRequest\x1a\x1b.demangle.v1.DetectResponse\x12;\n" +
	"\aSchemes\x12\x12.demangle.v1.Empty\x1a\x1c.demangle.v1.SchemesResponse\x12A\n" +
	"\x0eDemangleStream\x12\x14.demangle.v1.Request\x1a\x15.demangle.v1.Response(\x010\x01\x12V\n" +
	"\rUploadContext\x12!.demangle.v1.UploadContextRequest\x1a\".demangle.v1.UploadContextResponse\x12S\n" +
	"\fListContexts\x12 .demangle.v1.ListContextsRequest\x1a!.demangle.v1.ListContextsResponse\x12F\n" +
	"\rDeleteContext\x12!.demangle.v1.DeleteContextRequest\x1a\x12.demangle.v1.EmptyBNZLgithub.com/jelmerdehen/demangle/cmd/demanglegrpc/proto/demanglepb;demanglepbb\x06proto3"

var (
	file_demangle_proto_rawDescOnce sync.Once
	file_demangle_proto_rawDescData []byte
)

func file_demangle_proto_rawDescGZIP() []byte {
	file_demangle_proto_rawDescOnce.Do(func() {
		file_demangle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demangle_proto_rawDesc), len(file_demangle_proto_rawDesc)))
	})
	return file_demangle_proto_rawDescData
}

var file_demangle_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_demangle_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: demangle.v1.Empty
	(*Options)(nil),               // 1: demangle.v1.Options
	(*Request)(nil),               // 2: demangle.v1.Request
	(*Annotation)(nil),            // 3: demangle.v1.Annotation
	(*Node)(nil),                  // 4: demangle.v1.Node
	(*Error)(nil),                 // 5: demangle.v1.Error
	(*Response)(nil),              // 6: demangle.v1.Response
	(*DetectRequest)(nil),         // 7: demangle.v1.DetectRequest
	(*Candidate)(nil),             // 8: demangle.v1.Candidate
	(*DetectResponse)(nil),        // 9: demangle.v1.DetectResponse
	(*SchemeInfo)(nil),            // 10: demangle.v1.SchemeInfo
	(*SchemesResponse)(nil),       // 11: demangle.v1.SchemesResponse
	(*UploadContextRequest)(nil),  // 12: demangle.v1.UploadContextRequest
	(*UploadContextResponse)(nil), // 13: demangle.v1.UploadContextResponse
	(*ContextInfo)(nil),           // 14: demangle.v1.ContextInfo
	(*ListContextsRequest)(nil),   // 15: demangle.v1.ListContextsRequest
	(*ListContextsResponse)(nil),  // 16: demangle.v1.ListContextsResponse
	(*DeleteContextRequest)(nil),  // 17: demangle.v1.DeleteContextRequest
	nil,                           // 18: demangle.v1.Options.SchemeSpecificEntry
	nil,                           // 19: demangle.v1.UploadContextRequest.MetadataEntry
	nil,                           // 20: demangle.v1.ContextInfo.MetadataEntry
}
var file_demangle_proto_depIdxs = []int32{
	18, // 0: demangle.v1.Options.scheme_specific:type_name -> demangle.v1.Options.SchemeSpecificEntry
	1,  // 1: demangle.v1.Request.options:type_name -> demangle.v1.Options
	4,  // 2: demangle.v1.Node.children:type_name -> demangle.v1.Node
	3,  // 3: demangle.v1.Node.attrs:type_name -> demangle.v1.Annotation
	3,  // 4: demangle.v1.Response.annotations:type_name -> demangle.v1.Annotation
	4,  // 5: demangle.v1.Response.tree:type_name -> demangle.v1.Node
	5,  // 6: demangle.v1.Response.err:type_name -> demangle.v1.Error
	8,  // 7: demangle.v1.DetectResponse.candidates:type_name -> demangle.v1.Candidate
	10, // 8: demangle.v1.SchemesResponse.schemes:type_name -> demangle.v1.SchemeInfo
	19, // 9: demangle.v1.UploadContextRequest.metadata:type_name -> demangle.v1.UploadContextRequest.MetadataEntry
	20, // 10: demangle.v1.ContextInfo.metadata:type_name -> demangle.v1.ContextInfo.MetadataEntry
	14, // 11: demangle.v1.ListContextsResponse.contexts:type_name -> demangle.v1.ContextInfo
	2,  // 12: demangle.v1.Demangle.Demangle:input_type -> demangle.v1.Request
	7,  // 13: demangle.v1.Demangle.Detect:input_type -> demangle.v1.DetectRequest
	0,  // 14: demangle.v1.Demangle.Schemes:input_type -> demangle.v1.Empty
	2,  // 15: demangle.v1.Demangle.DemangleStream:input_type -> demangle.v1.Request
	12, // 16: demangle.v1.Demangle.UploadContext:input_type -> demangle.v1.UploadContextRequest
	15, // 17: demangle.v1.Demangle.ListContexts:input_type -> demangle.v1.ListContextsRequest
	17, // 18: demangle.v1.Demangle.DeleteContext:input_type -> demangle.v1.DeleteContextRequest
	6,  // 19: demangle.v1.Demangle.Demangle:output_type -> demangle.v1.Response
	9,  // 20: demangle.v1.Demangle.Detect:output_type -> demangle.v1.DetectResponse
	11, // 21: demangle.v1.Demangle.Schemes:output_type -> demangle.v1.SchemesResponse
	6,  // 22: demangle.v1.Demangle.DemangleStream:output_type -> demangle.v1.Response
	13, // 23: demangle.v1.Demangle.UploadContext:output_type -> demangle.v1.UploadContextResponse
	16, // 24: demangle.v1.Demangle.ListContexts:output_type -> demangle.v1.ListContextsResponse
	0,  // 25: demangle.v1.Demangle.DeleteContext:output_type -> demangle.v1.Empty
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_demangle_proto_init() }
func file_demangle_proto_init() {
	if File_demangle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demangle_proto_rawDesc), len(file_demangle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demangle_proto_goTypes,
		DependencyIndexes: file_demangle_proto_depIdxs,
		MessageInfos:      file_demangle_proto_msgTypes,
	}.Build()
	File_demangle_proto = out.File
	file_demangle_proto_goTypes = nil
	file_demangle_proto_depIdxs = nil
}
