// SPDX-License-Identifier: Apache-2.0

// Package production contains the production-scale corpus tests for the
// Swift stable demangler. Tests are build-tag gated:
//
//	go test -tags production_corpus ./scheme/swift/stable/testdata/production/
//
// Corpus files in corpus/ are generated by extract/Makefile (run on kodo).
// See production-divergences.txt for known mismatches.
package production
