// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Jelmer de Hen

package common

import (
	"testing"
	"unicode/utf8"
)

// knownPairs are (utf8, punycode) pairs produced by this implementation
// (Apple-variant alphabet: digits 0–25 → a–z, 26–35 → A–J).
// The encode column was generated by PunycodeEncode and verified to
// round-trip back to the utf8 column via PunycodeDecode.
var knownPairs = []struct {
	utf8     string
	punycode string
}{
	// Empty string.
	{"", ""},
	// Pure ASCII — basic code points emitted then delimiter.
	{"abc", "abc_"},
	{"hello", "hello_"},
	// Single non-ASCII rune. é = U+00E9
	{"é", "Jca"},
	// CJK: 中 = U+4E2D, 文 = U+6587
	{"中文", "fiqCCIc"},
	// Emoji: U+1F600 GRINNING FACE
	{"\U0001F600", "eCIh"},
	// Mixed ASCII + non-ASCII.
	{"café", "caf_dma"},
}

func TestPunycodeKnownPairs(t *testing.T) {
	t.Parallel()
	for _, tc := range knownPairs {
		tc := tc
		t.Run(tc.utf8, func(t *testing.T) {
			t.Parallel()
			got, err := PunycodeEncode(tc.utf8)
			if err != nil {
				t.Fatalf("Encode(%q): %v", tc.utf8, err)
			}
			if got != tc.punycode {
				t.Errorf("Encode(%q) = %q, want %q", tc.utf8, got, tc.punycode)
			}
			// Decode must round-trip back to the original.
			back, err := PunycodeDecode(tc.punycode)
			if err != nil {
				t.Fatalf("Decode(%q): %v", tc.punycode, err)
			}
			if back != tc.utf8 {
				t.Errorf("Decode(%q) = %q, want %q", tc.punycode, back, tc.utf8)
			}
		})
	}
}

func TestPunycodeRoundTrip(t *testing.T) {
	t.Parallel()
	cases := []string{
		"",
		"a",
		"Z",
		"abc",
		"é",           // é
		"中文",     // 中文
		"\U0001F600",       // 😀
		"αβγ", // αβγ
		"fooébar",
		"ABC", // ABC — all ASCII
		"àáâã", // àáâã
	}
	for _, s := range cases {
		s := s
		t.Run(s, func(t *testing.T) {
			t.Parallel()
			enc, err := PunycodeEncode(s)
			if err != nil {
				t.Fatalf("Encode(%q): %v", s, err)
			}
			dec, err := PunycodeDecode(enc)
			if err != nil {
				t.Fatalf("Decode(Encode(%q)=%q): %v", s, enc, err)
			}
			if dec != s {
				t.Errorf("round-trip(%q): got %q", s, dec)
			}
		})
	}
}

func TestPunycodeDecodeErrors(t *testing.T) {
	t.Parallel()
	bad := []string{
		"K",           // uppercase K is not in 'A'-'J', so invalid digit after empty prefix
		"\xff\xfe",   // invalid encoded chars
	}
	for _, s := range bad {
		s := s
		t.Run(s, func(t *testing.T) {
			t.Parallel()
			_, err := PunycodeDecode(s)
			if err == nil {
				t.Errorf("Decode(%q) expected error, got nil", s)
			}
		})
	}
}

// FuzzPunycodeRoundTrip tests Encode→Decode on arbitrary unicode text.
func FuzzPunycodeRoundTrip(f *testing.F) {
	// Seed with varied identifiers.
	seeds := []string{
		"",
		"abc",
		"中文",
		"\U0001F600",
		"αβγ",
		"fooé",
		"hello world",
		"àáâ",
	}
	for _, s := range seeds {
		f.Add(s)
	}
	f.Fuzz(func(t *testing.T, s string) {
		if !utf8.ValidString(s) {
			return
		}
		// Filter out surrogate-range runes which are invalid scalars.
		for _, r := range s {
			if r >= 0xD800 && r <= 0xDFFF {
				return
			}
		}
		enc, err := PunycodeEncode(s)
		if err != nil {
			return // not a valid input for this variant
		}
		dec, err := PunycodeDecode(enc)
		if err != nil {
			t.Fatalf("Decode(Encode(%q)=%q) failed: %v", s, enc, err)
		}
		if dec != s {
			t.Fatalf("round-trip mismatch: in=%q enc=%q out=%q", s, enc, dec)
		}
	})
}

// FuzzPunycodeDecodeEncode feeds arbitrary byte slices to Decode and,
// when successful, checks that re-encoding produces the same punycode.
func FuzzPunycodeDecodeEncode(f *testing.F) {
	seeds := []string{
		"abc_",
		"e_a",
		"fiq228c",
		"t28h",
		"hello_",
	}
	for _, s := range seeds {
		f.Add([]byte(s))
	}
	f.Fuzz(func(t *testing.T, b []byte) {
		s := string(b)
		dec, err := PunycodeDecode(s)
		if err != nil {
			return // invalid encoded form — skip
		}
		enc, err := PunycodeEncode(dec)
		if err != nil {
			t.Fatalf("Encode(Decode(%q)=%q) failed: %v", s, dec, err)
		}
		dec2, err := PunycodeDecode(enc)
		if err != nil {
			t.Fatalf("Decode(re-enc=%q) failed: %v", enc, err)
		}
		if dec2 != dec {
			t.Fatalf("decode-encode-decode mismatch: orig-dec=%q re-enc=%q re-dec=%q", dec, enc, dec2)
		}
	})
}
