// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Jelmer de Hen

package common

import (
	"testing"
	"unicode/utf8"
)

// knownPairs are (utf8, punycode) pairs produced by this implementation
// (Apple-variant alphabet: digits 0–25 → a–z, 26–35 → A–J).
// The encode column was generated by PunycodeEncode and verified to
// round-trip back to the utf8 column via PunycodeDecode.
var knownPairs = []struct {
	utf8     string
	punycode string
}{
	// Empty string.
	{"", ""},
	// Pure ASCII — basic code points emitted then delimiter.
	{"abc", "abc_"},
	{"hello", "hello_"},
	// Single non-ASCII rune. é = U+00E9
	{"é", "Jca"},
	// CJK: 中 = U+4E2D, 文 = U+6587
	{"中文", "fiqCCIc"},
	// Emoji: U+1F600 GRINNING FACE
	{"\U0001F600", "eCIh"},
	// Mixed ASCII + non-ASCII.
	{"café", "caf_dma"},
}

func TestPunycodeKnownPairs(t *testing.T) {
	t.Parallel()
	for _, tc := range knownPairs {
		tc := tc
		t.Run(tc.utf8, func(t *testing.T) {
			t.Parallel()
			got, err := PunycodeEncode(tc.utf8)
			if err != nil {
				t.Fatalf("Encode(%q): %v", tc.utf8, err)
			}
			if got != tc.punycode {
				t.Errorf("Encode(%q) = %q, want %q", tc.utf8, got, tc.punycode)
			}
			// Decode must round-trip back to the original.
			back, err := PunycodeDecode(tc.punycode)
			if err != nil {
				t.Fatalf("Decode(%q): %v", tc.punycode, err)
			}
			if back != tc.utf8 {
				t.Errorf("Decode(%q) = %q, want %q", tc.punycode, back, tc.utf8)
			}
		})
	}
}

func TestPunycodeRoundTrip(t *testing.T) {
	t.Parallel()
	cases := []string{
		"",
		"a",
		"Z",
		"abc",
		"é",           // é
		"中文",     // 中文
		"\U0001F600",       // 😀
		"αβγ", // αβγ
		"fooébar",
		"ABC", // ABC — all ASCII
		"àáâã", // àáâã
	}
	for _, s := range cases {
		s := s
		t.Run(s, func(t *testing.T) {
			t.Parallel()
			enc, err := PunycodeEncode(s)
			if err != nil {
				t.Fatalf("Encode(%q): %v", s, err)
			}
			dec, err := PunycodeDecode(enc)
			if err != nil {
				t.Fatalf("Decode(Encode(%q)=%q): %v", s, enc, err)
			}
			if dec != s {
				t.Errorf("round-trip(%q): got %q", s, dec)
			}
		})
	}
}

func TestPunycodeDecodeErrors(t *testing.T) {
	t.Parallel()
	bad := []string{
		"K",           // uppercase K is not in 'A'-'J', so invalid digit after empty prefix
		"\xff\xfe",   // invalid encoded chars
	}
	for _, s := range bad {
		s := s
		t.Run(s, func(t *testing.T) {
			t.Parallel()
			_, err := PunycodeDecode(s)
			if err == nil {
				t.Errorf("Decode(%q) expected error, got nil", s)
			}
		})
	}
}

// encodePunycodeRaw encodes []uint32 codepoints without any surrogate guard,
// for use in constructing test inputs that exercise the decoder's surrogate
// rejection path.
func encodePunycodeRaw(codePoints []uint32) (string, error) {
	out := make([]byte, 0, len(codePoints)+8)
	n := pInitialN
	delta := 0
	bias := pInitialBias
	h := 0
	for _, c := range codePoints {
		if c < 0x80 {
			h++
			out = append(out, byte(c))
		}
	}
	b := h
	if b > 0 {
		out = append(out, pDelimiter)
	}
	for h < len(codePoints) {
		m := uint32(0x10FFFF)
		for _, cp := range codePoints {
			if cp >= n && cp < m {
				m = cp
			}
		}
		mMinusN := int(m - n)
		if mMinusN > (1<<31-1-delta)/(h+1) {
			return "", errPunycodeOverflow
		}
		delta += mMinusN * (h + 1)
		n = m
		for _, c := range codePoints {
			if c < n {
				if delta == 1<<31-1 {
					return "", errPunycodeOverflow
				}
				delta++
			}
			if c == n {
				q := delta
				for k := pBase; ; k += pBase {
					t := k - bias
					if t < pTmin {
						t = pTmin
					} else if t > pTmax {
						t = pTmax
					}
					if q < t {
						break
					}
					out = append(out, digitValue(t+((q-t)%(pBase-t))))
					q = (q - t) / (pBase - t)
				}
				out = append(out, digitValue(q))
				bias = adaptBias(delta, h+1, h == b)
				delta = 0
				h++
			}
		}
		delta++
		n++
	}
	return string(out), nil
}

// TestPunycodeSurrogateEncode verifies that surrogate codepoints are rejected
// by the encoder with errPunycodeSurrogate.
func TestPunycodeSurrogateEncode(t *testing.T) {
	t.Parallel()
	surrogates := []struct {
		name string
		cp   uint32
	}{
		{"U+D800 (surrogate range start)", 0xD800},
		{"U+D87F (mid-low surrogate)", 0xD87F},
		{"U+DBFF (high surrogate end)", 0xDBFF},
		{"U+DC00 (low surrogate range start)", 0xDC00},
		{"U+DFFF (surrogate range end)", 0xDFFF},
	}
	for _, tc := range surrogates {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			// encodePunycode is the internal encoder; call it directly with a
			// surrogate codepoint to verify the guard fires.
			_, err := encodePunycode([]uint32{tc.cp})
			if err != errPunycodeSurrogate {
				t.Errorf("encodePunycode([U+%04X]) = %v, want errPunycodeSurrogate", tc.cp, err)
			}
		})
	}
}

// TestPunycodeSurrogateDecode verifies that surrogate codepoints are rejected
// by the decoder with errPunycodeSurrogate.
func TestPunycodeSurrogateDecode(t *testing.T) {
	t.Parallel()
	surrogates := []struct {
		name string
		cp   uint32
	}{
		{"U+D800", 0xD800},
		{"U+D87F", 0xD87F},
		{"U+DBFF", 0xDBFF},
		{"U+DC00", 0xDC00},
		{"U+DFFF", 0xDFFF},
	}
	for _, tc := range surrogates {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			// Produce the encoded form using encodePunycodeRaw (no surrogate
			// guard) so we can verify the decoder's rejection path.
			encoded, err := encodePunycodeRaw([]uint32{tc.cp})
			if err != nil {
				t.Fatalf("encodePunycodeRaw(U+%04X): %v", tc.cp, err)
			}
			_, err = PunycodeDecode(encoded)
			if err != errPunycodeSurrogate {
				t.Errorf("PunycodeDecode(encoded U+%04X) = %v, want errPunycodeSurrogate", tc.cp, err)
			}
		})
	}
}

// TestPunycodeValidUnicode verifies that valid non-ASCII codepoints still
// encode and decode correctly (regression guard against over-zealous surrogate
// rejection).
func TestPunycodeValidUnicode(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		s    string
	}{
		{"CJK U+4E16 世", "世"},
		{"emoji U+1F600 😀", "\U0001F600"},
		{"latin U+00E9 é", "é"},
		{"greek alpha U+03B1", "α"},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			enc, err := PunycodeEncode(tc.s)
			if err != nil {
				t.Fatalf("PunycodeEncode(%q): %v", tc.s, err)
			}
			dec, err := PunycodeDecode(enc)
			if err != nil {
				t.Fatalf("PunycodeDecode(%q): %v", enc, err)
			}
			if dec != tc.s {
				t.Errorf("round-trip(%q): got %q", tc.s, dec)
			}
		})
	}
}

// TestPunycodeAdversarial tests round-trip identity for edge-case inputs.
func TestPunycodeAdversarial(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name  string
		input string
	}{
		{"all-cjk", "数学関数"},
		{"single-greek", "α"},
		{"long-greek-31", "αβγδεζηθικλμνξοπρστυφχψωΑΒΓΔΕΖ"},
		{"mixed-ascii-cjk", "hello世界"},
		{"single-ascii", "x"},
		{"empty", ""},
		{"only-digits", "123"},
		{"emoji-party", "🎉"},
		{"high-codepoint", "\U0010FFFD"},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			encoded, err := PunycodeEncode(tt.input)
			if err != nil {
				t.Skipf("encode error (may be unsupported): %v", err)
			}
			decoded, err := PunycodeDecode(encoded)
			if err != nil {
				t.Errorf("decode(%q) error: %v", encoded, err)
				return
			}
			if decoded != tt.input {
				t.Errorf("round-trip: got %q, want %q", decoded, tt.input)
			}
		})
	}
}

// TestPunycodeEncodePureASCII verifies the pure-ASCII fast path.
// Apple's encoder always appends a trailing '_' delimiter when b > 0
// (there are basic code points), so pure-ASCII strings are returned
// with a trailing underscore.
func TestPunycodeEncodePureASCII(t *testing.T) {
	t.Parallel()
	cases := []struct {
		input string
		want  string
	}{
		{"hello", "hello_"},
		{"test123", "test123_"},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.input, func(t *testing.T) {
			t.Parallel()
			got, err := PunycodeEncode(tc.input)
			if err != nil {
				t.Fatalf("PunycodeEncode(%q): %v", tc.input, err)
			}
			if got != tc.want {
				t.Errorf("PunycodeEncode(%q) = %q, want %q", tc.input, got, tc.want)
			}
		})
	}
}

// FuzzPunycodeRoundTrip tests Encode→Decode on arbitrary unicode text.
func FuzzPunycodeRoundTrip(f *testing.F) {
	// Seed with varied identifiers.
	seeds := []string{
		"",
		"abc",
		"中文",
		"\U0001F600",
		"αβγ",
		"fooé",
		"hello world",
		"àáâ",
	}
	for _, s := range seeds {
		f.Add(s)
	}
	f.Fuzz(func(t *testing.T, s string) {
		if !utf8.ValidString(s) {
			return
		}
		// Filter out surrogate-range runes which are invalid scalars.
		for _, r := range s {
			if r >= 0xD800 && r <= 0xDFFF {
				return
			}
		}
		enc, err := PunycodeEncode(s)
		if err != nil {
			return // not a valid input for this variant
		}
		dec, err := PunycodeDecode(enc)
		if err != nil {
			t.Fatalf("Decode(Encode(%q)=%q) failed: %v", s, enc, err)
		}
		if dec != s {
			t.Fatalf("round-trip mismatch: in=%q enc=%q out=%q", s, enc, dec)
		}
	})
}

// FuzzPunycodeDecodeEncode feeds arbitrary byte slices to Decode and,
// when successful, checks that re-encoding produces the same punycode.
func FuzzPunycodeDecodeEncode(f *testing.F) {
	seeds := []string{
		"abc_",
		"e_a",
		"fiq228c",
		"t28h",
		"hello_",
	}
	for _, s := range seeds {
		f.Add([]byte(s))
	}
	f.Fuzz(func(t *testing.T, b []byte) {
		s := string(b)
		dec, err := PunycodeDecode(s)
		if err != nil {
			return // invalid encoded form — skip
		}
		enc, err := PunycodeEncode(dec)
		if err != nil {
			t.Fatalf("Encode(Decode(%q)=%q) failed: %v", s, dec, err)
		}
		dec2, err := PunycodeDecode(enc)
		if err != nil {
			t.Fatalf("Decode(re-enc=%q) failed: %v", enc, err)
		}
		if dec2 != dec {
			t.Fatalf("decode-encode-decode mismatch: orig-dec=%q re-enc=%q re-dec=%q", dec, enc, dec2)
		}
	})
}
